name: CI

on:
  push:
    branches: [ main ]

jobs:
  DESENVOLVIMENTO: # Aqui ele cria uma máquina virtual utilizando a última versão do Ubuntu
    runs-on: ubuntu-latest
    steps: # Aqui ele baixa o código para essa máquina virtual
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Aqui ele baixa o Node.js na máquina virtual
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - run: npm install  # Baixa as dependências do projeto
      - run: npm ci       # npm ci baixa o arquivo package-lock.json na maquina virtual assim tirando erros futuros de compatibilidade

 # Aqui ele executa a validação de Conventional Commits
  ValidacaoConventionalCommits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

     
      - name: Validação Conventional Commits
        run: |
          npm install -g conventional-changelog-lint
          conventional-changelog-lint --from main --to HEAD


  SemanticRelease:
    runs-on: ubuntu-latest
    needs: [ValidacaoConventionalCommits]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install dependencies
        run: npm install

      - name: Run semantic-release
        run: npm semantic-release
