name: CI

on:
  push:
    branches: [ main ]

jobs:
  DESENVOLVIMENTO: # Aqui ele cria uma máquina virtual utilizando a última versão do Ubuntu
    runs-on: ubuntu-latest
    steps: # Aqui ele baixa o código para essa máquina virtual
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Aqui ele baixa o Node.js na máquina virtual
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 12

      - run: npm install  # Baixa as dependências do projeto
      - run: npm ci       # npm ci baixa o arquivo package-lock.json na maquina virtual assim tirando erros futuros de compatibilidade

 # Aqui ele executa a validação de Conventional Commits
  ValidacaoConventionalCommits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 12
     
      - name: Validação Conventional Commits
        run: |
          npm install -g conventional-changelog-lint
          conventional-changelog-lint --from main --to HEAD
          
          
      - run: chmod +x node_modules/.bin/semantic-release
      
      - name: Run semantic-release
        env:
         GH_TOKEN: ${{ secrets.GH_TOKEdN }} 
        run: npx -p node@v20-lts -c "npx semantic-release"
        

